### ISSUE TITLE
Drop KernelSU in favor of APatch?

### ISSUE THREAD

**Issue by Dozairu** [samsungexynos850/KawaKernel-A217X#1]
KernelSU no longer supports non-GKI kernels where v0.9.5 is the last supported version. This brings concern as if there were critical security issues fixed upstream, we would have to fork our own KernelSU to backport those fixes, and it is very inconvenient.

Dropping KernelSU for APatch will ensure that users will have continued support for their root solution.
The downside is installing APatch requires users to know what are they doing and migrating to APatch would mean setting up your modules all over again.

https://apatch.dev/

**Comment by RiskyGUY22** [comment]
We can change the kernelSU submodule to use a version with backports

**Comment by DozNaka** [comment]
Solved by switching to a repo that backported v1.0.1 to 4.19

https://github.com/samsungexynos850/KawaKernel-A217X/commit/453681891e2bdc08cbf2d4dd2672e08085977c56
